# Generated by Django 5.0.3 on 2024-03-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField()),
                ('full_name', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=200)),
                ('surnames', models.CharField(max_length=200)),
                ('birthdate', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
