# Generated by Django 5.0.3 on 2024-03-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_origen1_created_origen1_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='origen1',
            name='origin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
